### PR TITLE
Issue 473/http connections can be used before they are ready

### LINKED ISSUE #473: Http connections can be used before they are ready
When looking at issue #469. I noticed that it is possible to use http connections before they are ready. Before they are ready has 2 meanings:
1. Before connection is ready the first time, so setup time
2. Before we can reuse a connection, time it takes to recycle a connection (should not be a problem for http2 in most cases because we can multiplex there)

When using a connection pool we sometimes hit 2 when using http1.1 . This only happens very rarely and we only noticed this because we removed the retryLayer from that specific example so we would see all errors (even this unexpected one).

I'm opening this separate issue because I think this problem is unrelated to the connection pool recycling this connection to early. For that we need to implement a `is_ready` mechanism in the connection pool itself. 

But this problem also occurs without a connection pool, we just haven't noticed it yet because almost all other examples/tests use a retryLayer. Hitting 2 is possible when constructing a custom httpClient where you open a single connection and reuse it for multiple request (similar to connection pool, but much easier), and 1 might also be possible, but that probably depends on how these connections are created (didn't test/check this yet).

@GlenDC also mentioned that `pub fn send_request(&self, req: Request<B>)` originally was of type `pub fn send_request(&mut self, req: Request<B>)`. We might want to change this back as `pub fn ready(&mut self)` is also of that type, and this also signals that only one user should be using this at the same time. Not sure if we also want todo that for http2 as there we have an unbounded dispatcher, but seeing that `ready` there is also `&mut self` why not?

In the future we probably want a lot more tests without retryLayers as these can hide important bugs.

### PR DESCRIPTION
**Pull request by soundofspace**
Fixes #473 .
- Wait for http connections to be ready before using them so we dont crash/error on connection not ready
- For http1 we need to mutex and lock to support this -> 1 by 1 = pipelining but consecutive
- For http2 we can clone sender todo this -> multiplexing
- Add mock connector svc in conn.rs, so we can start testing services/connectors all over the place without needed to re-invent this concept (eg stuff like ua_emulating can start using this also in the future). This way we can test each network layer separately without having to fallback to integration tests
- Add testing to verify that pipelining and multiplexing works as expected
- Change `send_request` fn signature to `&mut self` instead of `&self`. This way we are in sync again with hyper. This function signature also makes it a lot hard to abuse these connections, especially for http1.1
- `http_core_end_to_end` can now also support parrallell http1.1 benchmarks by using the same pipeline mechanism

### CODE REVIEW

**Comment by soundofspace** [comment]
http_core_end_to_end on this branch:
```
└> cargo bench --bench=http_core_end_to_end --features=full
   Compiling rama v0.2.0-alpha.8 (/Volumes/home/projects/open/rama)
    Finished `bench` profile [optimized] target(s) in 8.91s
     Running benches/http_core_end_to_end.rs (target/release/deps/http_core_end_to_end-9bf1f78b9fa7d22e)
Timer precision: 41 ns
http_core_end_to_end                                       fastest       │ slowest       │ median        │ mean          │ samples │ iters
├─ http1_consecutive_x1_both_10mb                          1.64 ms       │ 9.714 ms      │ 1.894 ms      │ 2.122 ms      │ 100     │ 100
│                                                          12.78 GB/s    │ 2.158 GB/s    │ 11.06 GB/s    │ 9.881 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            19          │ 31            │ 19            │ 19.11         │         │
│                                                            419.2 KB    │ 1.46 MB       │ 419.2 KB      │ 432.3 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            151         │ 283           │ 151           │ 153.4         │         │
│                                                            844.3 KB    │ 456.9 KB      │ 844.3 KB      │ 822.3 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            151         │ 269           │ 151           │ 153.2         │         │
│                                                            844.3 KB    │ 528.6 KB      │ 844.3 KB      │ 828.1 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            0           │ 10            │ 0             │ 0.11          │         │
│                                                            0 B         │ 1.015 MB      │ 0 B           │ 14.33 KB      │         │
├─ http1_consecutive_x1_both_100kb                         28.72 µs      │ 188.4 µs      │ 32.9 µs       │ 36.62 µs      │ 100     │ 100
│                                                          7.128 GB/s    │ 1.086 GB/s    │ 6.223 GB/s    │ 5.591 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            20          │ 30            │ 19            │ 19.82         │         │
│                                                            132.8 KB    │ 264.7 KB      │ 132.4 KB      │ 139.2 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            49          │ 73            │ 53            │ 51.39         │         │
│                                                            267.6 KB    │ 163.5 KB      │ 267.7 KB      │ 255.6 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            49          │ 61            │ 53            │ 51.26         │         │
│                                                            267.6 KB    │ 251.6 KB      │ 267.7 KB      │ 264.2 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            0           │ 6             │ 0             │ 0.13          │         │
│                                                            0 B         │ 229.3 KB      │ 0 B           │ 11.46 KB      │         │
├─ http1_consecutive_x1_empty                              14.99 µs      │ 43.95 µs      │ 17.72 µs      │ 19.22 µs      │ 100     │ 100
│                                                          0 B/s         │ 0 B/s         │ 0 B/s         │ 0 B/s         │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            11          │ 11            │ 11            │ 11.1          │         │
│                                                            9.228 KB    │ 9.228 KB      │ 9.228 KB      │ 9.571 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            22          │ 22            │ 22            │ 22.11         │         │
│                                                            19.82 KB    │ 19.82 KB      │ 19.82 KB      │ 20.17 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            22          │ 22            │ 22            │ 22            │         │
│                                                            19.82 KB    │ 19.82 KB      │ 19.82 KB      │ 19.82 KB      │         │
├─ http1_consecutive_x1_req_10b                            17.45 µs      │ 59.12 µs      │ 20.22 µs      │ 21.09 µs      │ 100     │ 100
│                                                          572.8 KB/s    │ 169.1 KB/s    │ 494.3 KB/s    │ 474 KB/s      │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            20          │ 20            │ 20            │ 20.11         │         │
│                                                            9.982 KB    │ 9.982 KB      │ 9.982 KB      │ 10.32 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            40          │ 40            │ 40            │ 40.12         │         │
│                                                            21.31 KB    │ 21.31 KB      │ 21.31 KB      │ 21.65 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            40          │ 40            │ 40            │ 40            │         │
│                                                            21.31 KB    │ 21.31 KB      │ 21.31 KB      │ 21.31 KB      │         │
├─ http1_parallel_x10_empty                                157.4 µs      │ 300.8 µs      │ 176.3 µs      │ 182.9 µs      │ 100     │ 100
│                                                          0 B/s         │ 0 B/s         │ 0 B/s         │ 0 B/s         │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            12          │ 12            │ 12            │ 12.11         │         │
│                                                            17.06 KB    │ 17.06 KB      │ 17.06 KB      │ 17.41 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            221         │ 221           │ 221           │ 221.1         │         │
│                                                            206.1 KB    │ 206.1 KB      │ 206.1 KB      │ 206.4 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            221         │ 221           │ 221           │ 221           │         │
│                                                            206.1 KB    │ 206.1 KB      │ 206.1 KB      │ 206.1 KB      │         │
├─ http1_parallel_x10_req_10kb_100_chunks                  2.654 ms      │ 8.579 ms      │ 2.73 ms       │ 2.873 ms      │ 100     │ 100
│                                                          3.857 GB/s    │ 1.193 GB/s    │ 3.75 GB/s     │ 3.563 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            102         │ 102           │ 102           │ 102.1         │         │
│                                                            24.47 KB    │ 24.47 KB      │ 24.47 KB      │ 29.88 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            4409        │ 4407          │ 4414          │ 4411          │         │
│                                                            328.8 KB    │ 328.7 KB      │ 328.9 KB      │ 329.2 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            4409        │ 4407          │ 4414          │ 4411          │         │
│                                                            328.8 KB    │ 328.7 KB      │ 328.9 KB      │ 328.8 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            0           │ 0             │ 0             │ 0.05          │         │
│                                                            0 B         │ 0 B           │ 0 B           │ 5.079 KB      │         │
├─ http1_parallel_x10_req_10mb                             9.171 ms      │ 12.66 ms      │ 9.681 ms      │ 9.914 ms      │ 100     │ 100
│                                                          11.43 GB/s    │ 8.279 GB/s    │ 10.83 GB/s    │ 10.57 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            29          │ 29            │ 29            │ 29.11         │         │
│                                                            427.3 KB    │ 427.3 KB      │ 427.3 KB      │ 434.3 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            901         │ 901           │ 901           │ 902.1         │         │
│                                                            4.332 MB    │ 4.332 MB      │ 4.332 MB      │ 4.317 MB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            901         │ 901           │ 901           │ 902           │         │
│                                                            4.332 MB    │ 4.332 MB      │ 4.332 MB      │ 4.326 MB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            0           │ 0             │ 0             │ 0.07          │         │
│                                                            0 B         │ 0 B           │ 0 B           │ 13.43 KB      │         │
├─ http1_parallel_x10_res_1mb                              1.012 ms      │ 1.764 ms      │ 1.097 ms      │ 1.148 ms      │ 100     │ 100
│                                                          10.35 GB/s    │ 5.943 GB/s    │ 9.55 GB/s     │ 9.129 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            20          │ 31            │ 20            │ 20.12         │         │
│                                                            426.2 KB    │ 960.3 KB      │ 426.2 KB      │ 431.6 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            351         │ 390           │ 352           │ 353.3         │         │
│                                                            4.309 MB    │ 994 KB        │ 4.309 MB      │ 4.276 MB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            351         │ 379           │ 352           │ 353.1         │         │
│                                                            4.309 MB    │ 1.066 MB      │ 4.309 MB      │ 4.276 MB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            0           │ 5             │ 0             │ 0.05          │         │
│                                                            0 B         │ 507.9 KB      │ 0 B           │ 5.079 KB      │         │
├─ http1_parallel_x10_res_10mb                             8.665 ms      │ 11.69 ms      │ 9.148 ms      │ 9.277 ms      │ 100     │ 100
│                                                          12.1 GB/s     │ 8.963 GB/s    │ 11.46 GB/s    │ 11.3 GB/s     │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            19          │ 19            │ 19            │ 19.12         │         │
│                                                            426.2 KB    │ 426.2 KB      │ 426.2 KB      │ 431.6 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            811         │ 811           │ 811           │ 812.3         │         │
│                                                            4.323 MB    │ 4.323 MB      │ 4.323 MB      │ 4.319 MB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            811         │ 811           │ 811           │ 812.1         │         │
│                                                            4.323 MB    │ 4.323 MB      │ 4.323 MB      │ 4.32 MB       │         │
│                                                          grow:         │               │               │               │         │
│                                                            0           │ 0             │ 0             │ 0.05          │         │
│                                                            0 B         │ 0 B           │ 0 B           │ 5.079 KB      │         │
├─ http2_consecutive_x1_empty                              19.6 µs       │ 163.9 µs      │ 22.06 µs      │ 24.44 µs      │ 100     │ 100
│                                                          0 B/s         │ 0 B/s         │ 0 B/s         │ 0 B/s         │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            9           │ 47            │ 9             │ 9.39          │         │
│                                                            4.352 KB    │ 44.89 KB      │ 4.352 KB      │ 4.842 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            26          │ 63            │ 26            │ 26.38         │         │
│                                                            6.597 KB    │ 48.33 KB      │ 6.597 KB      │ 7.099 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            26          │ 25            │ 26            │ 25.99         │         │
│                                                            6.605 KB    │ 6.63 KB       │ 6.605 KB      │ 6.605 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            1           │ 4             │ 1             │ 1.03          │         │
│                                                            8 B         │ 48 B          │ 8 B           │ 8.4 B         │         │
├─ http2_consecutive_x1_req_10b                            21.12 µs      │ 98.88 µs      │ 23.62 µs      │ 26.25 µs      │ 100     │ 100
│                                                          473.2 KB/s    │ 101.1 KB/s    │ 423.1 KB/s    │ 380.8 KB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            13          │ 13            │ 13            │ 13.34         │         │
│                                                            4.352 KB    │ 4.352 KB      │ 4.352 KB      │ 4.842 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            36          │ 36            │ 36            │ 36.37         │         │
│                                                            8.267 KB    │ 8.267 KB      │ 8.267 KB      │ 8.768 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            36          │ 36            │ 36            │ 35.99         │         │
│                                                            8.275 KB    │ 8.275 KB      │ 8.275 KB      │ 8.275 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            1           │ 1             │ 1             │ 1.03          │         │
│                                                            8 B         │ 8 B           │ 8 B           │ 8.4 B         │         │
├─ http2_consecutive_x1_req_100kb                          43.34 µs      │ 164.6 µs      │ 48.11 µs      │ 52.25 µs      │ 100     │ 100
│                                                          2.362 GB/s    │ 621.8 MB/s    │ 2.128 GB/s    │ 1.959 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            24          │ 24            │ 24            │ 24.24         │         │
│                                                            106.7 KB    │ 106.7 KB      │ 106.7 KB      │ 106.8 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            48          │ 48            │ 48            │ 48.37         │         │
│                                                            57.66 KB    │ 57.66 KB      │ 57.66 KB      │ 58.16 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            48          │ 48            │ 48            │ 47.99         │         │
│                                                            111 KB      │ 111 KB        │ 111 KB        │ 110.9 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            8           │ 8             │ 8             │ 8.03          │         │
│                                                            53.36 KB    │ 53.36 KB      │ 53.36 KB      │ 53.33 KB      │         │
├─ http2_parallel_x10_empty                                58.26 µs      │ 145 µs        │ 61.69 µs      │ 65.51 µs      │ 100     │ 100
│                                                          0 B/s         │ 0 B/s         │ 0 B/s         │ 0 B/s         │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            91          │ 128           │ 91            │ 91.4          │         │
│                                                            43 KB       │ 103.8 KB      │ 43 KB         │ 43.74 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            261         │ 301           │ 261           │ 261.4         │         │
│                                                            73.81 KB    │ 115.9 KB      │ 73.81 KB      │ 74.36 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            261         │ 264           │ 261           │ 261           │         │
│                                                            73.89 KB    │ 74.16 KB      │ 73.89 KB      │ 73.89 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            10          │ 31            │ 10            │ 10.21         │         │
│                                                            80 B        │ 22.8 KB       │ 80 B          │ 307.2 B       │         │
├─ http2_parallel_x10_req_10kb_100_chunks                  3.566 ms      │ 8.232 ms      │ 3.679 ms      │ 3.966 ms      │ 100     │ 100
│                                                          2.87 GB/s     │ 1.243 GB/s    │ 2.782 GB/s    │ 2.581 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            209         │ 194           │ 209           │ 202           │         │
│                                                            578.8 KB    │ 480.3 KB      │ 578.8 KB      │ 531.7 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            4347        │ 4319          │ 4341          │ 4344          │         │
│                                                            9.461 MB    │ 9.331 MB      │ 9.433 MB      │ 9.45 MB       │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            4347        │ 4319          │ 4341          │ 4344          │         │
│                                                            13.51 MB    │ 13.34 MB      │ 13.46 MB      │ 13.49 MB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            505         │ 500           │ 502.5         │ 503.9         │         │
│                                                            4.055 MB    │ 4.014 MB      │ 4.034 MB      │ 4.045 MB      │         │
├─ http2_parallel_x10_req_10kb_100_chunks_adaptive_window  3.512 ms      │ 5.205 ms      │ 3.674 ms      │ 3.918 ms      │ 100     │ 100
│                                                          2.915 GB/s    │ 1.966 GB/s    │ 2.786 GB/s    │ 2.613 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            193         │ 198           │ 193.5         │ 198.2         │         │
│                                                            484.3 KB    │ 384.1 KB      │ 489.3 KB      │ 472.9 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            4307        │ 4387          │ 4307          │ 4326          │         │
│                                                            9.276 MB    │ 9.646 MB      │ 9.276 MB      │ 9.364 MB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            4307        │ 4387          │ 4307          │ 4326          │         │
│                                                            13.24 MB    │ 13.56 MB      │ 13.24 MB      │ 13.32 MB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            495         │ 489           │ 495           │ 493.9         │         │
│                                                            3.973 MB    │ 3.923 MB      │ 3.973 MB      │ 3.962 MB      │         │
├─ http2_parallel_x10_req_10kb_100_chunks_max_window       3.37 ms       │ 4.722 ms      │ 3.497 ms      │ 3.597 ms      │ 100     │ 100
│                                                          3.037 GB/s    │ 2.168 GB/s    │ 2.927 GB/s    │ 2.846 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            193         │ 193           │ 193           │ 194.2         │         │
│                                                            497.3 KB    │ 471.9 KB      │ 497.3 KB      │ 503.9 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            4283        │ 4291          │ 4283          │ 4289          │         │
│                                                            9.165 MB    │ 9.202 MB      │ 9.165 MB      │ 9.195 MB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            4283        │ 4291          │ 4283          │ 4289          │         │
│                                                            13.11 MB    │ 13.15 MB      │ 13.1 MB       │ 13.13 MB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            492         │ 493           │ 490.5         │ 491.7         │         │
│                                                            3.948 MB    │ 3.956 MB      │ 3.936 MB      │ 3.944 MB      │         │
├─ http2_parallel_x10_req_10mb                             24.61 ms      │ 36.41 ms      │ 25.99 ms      │ 27.15 ms      │ 100     │ 100
│                                                          4.259 GB/s    │ 2.879 GB/s    │ 4.034 GB/s    │ 3.861 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            251         │ 251           │ 251           │ 250.5         │         │
│                                                            1.1 MB      │ 1.1 MB        │ 1.1 MB        │ 1.101 MB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            13162       │ 13162         │ 13162         │ 13162         │         │
│                                                            52.77 MB    │ 52.77 MB      │ 52.77 MB      │ 52.77 MB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            13162       │ 13162         │ 13162         │ 13162         │         │
│                                                            105.2 MB    │ 105.2 MB      │ 105.2 MB      │ 105.2 MB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            6420        │ 6420          │ 6420          │ 6420          │         │
│                                                            52.48 MB    │ 52.48 MB      │ 52.48 MB      │ 52.48 MB      │         │
├─ http2_parallel_x10_res_1mb                              2.455 ms      │ 4.211 ms      │ 2.675 ms      │ 2.85 ms       │ 100     │ 100
│                                                          4.27 GB/s     │ 2.489 GB/s    │ 3.919 GB/s    │ 3.679 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            240         │ 240           │ 240.5         │ 239.7         │         │
│                                                            1.1 MB      │ 1.1 MB        │ 1.104 MB      │ 1.101 MB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            1572        │ 1572          │ 1572          │ 1572          │         │
│                                                            5.342 MB    │ 5.342 MB      │ 5.347 MB      │ 5.343 MB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            1572        │ 1572          │ 1572          │ 1572          │         │
│                                                            10.59 MB    │ 10.59 MB      │ 10.59 MB      │ 10.59 MB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            660         │ 660           │ 660           │ 660.2         │         │
│                                                            5.248 MB    │ 5.248 MB      │ 5.248 MB      │ 5.249 MB      │         │
╰─ http2_parallel_x10_res_10mb                             23.87 ms      │ 32.56 ms      │ 26.33 ms      │ 26.86 ms      │ 100     │ 100
                                                           4.391 GB/s    │ 3.219 GB/s    │ 3.982 GB/s    │ 3.903 GB/s    │         │
                                                           max alloc:    │               │               │               │         │
                                                             240         │ 211           │ 240           │ 239.8         │         │
                                                             1.1 MB      │ 1.158 MB      │ 1.1 MB        │ 1.101 MB      │         │
                                                           alloc:        │               │               │               │         │
                                                             13092       │ 13131         │ 13092         │ 13092         │         │
                                                             52.75 MB    │ 52.8 MB       │ 52.75 MB      │ 52.75 MB      │         │
                                                           dealloc:      │               │               │               │         │
                                                             13092       │ 13095         │ 13092         │ 13092         │         │
                                                             105.2 MB    │ 105.2 MB      │ 105.2 MB      │ 105.2 MB      │         │
                                                           grow:         │               │               │               │         │
                                                             6420        │ 6444          │ 6420          │ 6420          │         │
                                                             52.48 MB    │ 52.52 MB      │ 52.48 MB      │ 52.48 MB      │         │
```

 http_core_end_to_end on main:
```
http_core_end_to_end                                       fastest       │ slowest       │ median        │ mean          │ samples │ iters
├─ http1_consecutive_x1_both_10mb                          1.707 ms      │ 9.702 ms      │ 1.813 ms      │ 2.074 ms      │ 100     │ 100
│                                                          12.28 GB/s    │ 2.161 GB/s    │ 11.56 GB/s    │ 10.11 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            19          │ 31            │ 19            │ 19.1          │         │
│                                                            419.2 KB    │ 1.46 MB       │ 419.2 KB      │ 429.6 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            151         │ 236           │ 151           │ 152.8         │         │
│                                                            844.3 KB    │ 455.4 KB      │ 844.3 KB      │ 819.6 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            151         │ 223           │ 151           │ 152.7         │         │
│                                                            844.3 KB    │ 527.1 KB      │ 844.3 KB      │ 821.2 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            0           │ 10            │ 0             │ 0.1           │         │
│                                                            0 B         │ 1.015 MB      │ 0 B           │ 10.15 KB      │         │
├─ http1_consecutive_x1_both_100kb                         29.82 µs      │ 123.7 µs      │ 32.81 µs      │ 34.84 µs      │ 100     │ 100
│                                                          6.867 GB/s    │ 1.655 GB/s    │ 6.241 GB/s    │ 5.878 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            20          │ 30            │ 20            │ 19.85         │         │
│                                                            132.8 KB    │ 264.6 KB      │ 132.4 KB      │ 138.5 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            49          │ 72            │ 51            │ 51.52         │         │
│                                                            267.6 KB    │ 163.4 KB      │ 267.7 KB      │ 260.8 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            49          │ 61            │ 51            │ 51.4          │         │
│                                                            267.6 KB    │ 251.6 KB      │ 267.7 KB      │ 268.2 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            0           │ 6             │ 0             │ 0.12          │         │
│                                                            0 B         │ 229.3 KB      │ 0 B           │ 10.15 KB      │         │
├─ http1_consecutive_x1_empty                              14.48 µs      │ 94.85 µs      │ 18.35 µs      │ 20.93 µs      │ 100     │ 100
│                                                          0 B/s         │ 0 B/s         │ 0 B/s         │ 0 B/s         │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            11          │ 11            │ 11            │ 11.1          │         │
│                                                            9.228 KB    │ 9.228 KB      │ 9.228 KB      │ 9.571 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            22          │ 22            │ 22            │ 22.1          │         │
│                                                            19.82 KB    │ 19.82 KB      │ 19.82 KB      │ 20.16 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            22          │ 22            │ 22            │ 22            │         │
│                                                            19.82 KB    │ 19.82 KB      │ 19.82 KB      │ 19.82 KB      │         │
├─ http1_consecutive_x1_req_10b                            16.01 µs      │ 67.76 µs      │ 19.97 µs      │ 21.94 µs      │ 100     │ 100
│                                                          624.4 KB/s    │ 147.5 KB/s    │ 500.7 KB/s    │ 455.6 KB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            20          │ 20            │ 20            │ 20.11         │         │
│                                                            9.982 KB    │ 9.982 KB      │ 9.982 KB      │ 10.32 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            40          │ 40            │ 40            │ 40.11         │         │
│                                                            21.31 KB    │ 21.31 KB      │ 21.31 KB      │ 21.65 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            40          │ 40            │ 40            │ 40            │         │
│                                                            21.31 KB    │ 21.31 KB      │ 21.31 KB      │ 21.31 KB      │         │
├─ http1_parallel_x10_empty                                (ignored)     │               │               │               │         │
├─ http1_parallel_x10_req_10kb_100_chunks                  (ignored)     │               │               │               │         │
├─ http1_parallel_x10_req_10mb                             (ignored)     │               │               │               │         │
├─ http1_parallel_x10_res_1mb                              (ignored)     │               │               │               │         │
├─ http1_parallel_x10_res_10mb                             (ignored)     │               │               │               │         │
├─ http2_consecutive_x1_empty                              19.92 µs      │ 140.5 µs      │ 22.52 µs      │ 26.18 µs      │ 100     │ 100
│                                                          0 B/s         │ 0 B/s         │ 0 B/s         │ 0 B/s         │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            9           │ 47            │ 9             │ 9.39          │         │
│                                                            4.352 KB    │ 44.89 KB      │ 4.352 KB      │ 4.842 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            26          │ 63            │ 26            │ 26.38         │         │
│                                                            6.597 KB    │ 48.33 KB      │ 6.597 KB      │ 7.099 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            26          │ 25            │ 26            │ 25.99         │         │
│                                                            6.605 KB    │ 6.63 KB       │ 6.605 KB      │ 6.605 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            1           │ 4             │ 1             │ 1.03          │         │
│                                                            8 B         │ 48 B          │ 8 B           │ 8.4 B         │         │
├─ http2_consecutive_x1_req_10b                            20.85 µs      │ 61.97 µs      │ 23.29 µs      │ 24.03 µs      │ 100     │ 100
│                                                          479.5 KB/s    │ 161.3 KB/s    │ 429.3 KB/s    │ 416.1 KB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            13          │ 46            │ 13            │ 13.34         │         │
│                                                            4.352 KB    │ 44.87 KB      │ 4.352 KB      │ 4.842 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            36          │ 72            │ 36            │ 36.37         │         │
│                                                            8.267 KB    │ 49.98 KB      │ 8.267 KB      │ 8.768 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            36          │ 35            │ 36            │ 35.99         │         │
│                                                            8.275 KB    │ 8.3 KB        │ 8.275 KB      │ 8.275 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            1           │ 4             │ 1             │ 1.03          │         │
│                                                            8 B         │ 48 B          │ 8 B           │ 8.4 B         │         │
├─ http2_consecutive_x1_req_100kb                          44.93 µs      │ 149.5 µs      │ 50.86 µs      │ 56.84 µs      │ 100     │ 100
│                                                          2.278 GB/s    │ 684.8 MB/s    │ 2.013 GB/s    │ 1.801 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            24          │ 24            │ 24            │ 24.27         │         │
│                                                            106.7 KB    │ 106.7 KB      │ 106.7 KB      │ 106.8 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            48          │ 48            │ 48            │ 48.37         │         │
│                                                            57.66 KB    │ 57.66 KB      │ 57.66 KB      │ 58.16 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            48          │ 48            │ 48            │ 47.99         │         │
│                                                            111 KB      │ 111 KB        │ 111 KB        │ 110.9 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            8           │ 8             │ 8             │ 8.03          │         │
│                                                            53.36 KB    │ 53.36 KB      │ 53.36 KB      │ 53.33 KB      │         │
├─ http2_parallel_x10_empty                                58.2 µs       │ 133.7 µs      │ 63.89 µs      │ 68.8 µs       │ 100     │ 100
│                                                          0 B/s         │ 0 B/s         │ 0 B/s         │ 0 B/s         │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            91          │ 91            │ 91            │ 91.4          │         │
│                                                            40.36 KB    │ 40.36 KB      │ 40.36 KB      │ 41.1 KB       │         │
│                                                          alloc:        │               │               │               │         │
│                                                            261         │ 261           │ 261           │ 261.4         │         │
│                                                            71.17 KB    │ 71.17 KB      │ 71.17 KB      │ 71.72 KB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            261         │ 261           │ 261           │ 261           │         │
│                                                            71.25 KB    │ 71.25 KB      │ 71.25 KB      │ 71.25 KB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            10          │ 10            │ 10            │ 10.21         │         │
│                                                            80 B        │ 80 B          │ 80 B          │ 307.2 B       │         │
├─ http2_parallel_x10_req_10kb_100_chunks                  3.514 ms      │ 5.506 ms      │ 3.603 ms      │ 3.806 ms      │ 100     │ 100
│                                                          2.913 GB/s    │ 1.859 GB/s    │ 2.841 GB/s    │ 2.689 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            212         │ 193           │ 202.5         │ 205.2         │         │
│                                                            594.6 KB    │ 469.3 KB      │ 531.9 KB      │ 552.9 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            4299        │ 4315          │ 4307          │ 4307          │         │
│                                                            9.236 MB    │ 9.31 MB       │ 9.273 MB      │ 9.273 MB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            4299        │ 4315          │ 4307          │ 4306          │         │
│                                                            13.2 MB     │ 13.3 MB       │ 13.23 MB      │ 13.24 MB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            494         │ 497           │ 493           │ 494.4         │         │
│                                                            3.965 MB    │ 3.989 MB      │ 3.956 MB      │ 3.967 MB      │         │
├─ http2_parallel_x10_req_10kb_100_chunks_adaptive_window  3.57 ms       │ 5.673 ms      │ 3.72 ms       │ 3.976 ms      │ 100     │ 100
│                                                          2.868 GB/s    │ 1.804 GB/s    │ 2.752 GB/s    │ 2.574 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            194         │ 199           │ 212           │ 203.6         │         │
│                                                            486.6 KB    │ 382 KB        │ 542.8 KB      │ 517 KB        │         │
│                                                          alloc:        │               │               │               │         │
│                                                            4323        │ 4359          │ 4315          │ 4323          │         │
│                                                            9.347 MB    │ 9.514 MB      │ 9.31 MB       │ 9.349 MB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            4323        │ 4359          │ 4315          │ 4323          │         │
│                                                            13.33 MB    │ 13.38 MB      │ 13.29 MB      │ 13.33 MB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            497         │ 484           │ 496           │ 497           │         │
│                                                            3.989 MB    │ 3.883 MB      │ 3.981 MB      │ 3.988 MB      │         │
├─ http2_parallel_x10_req_10kb_100_chunks_max_window       3.52 ms       │ 7.22 ms       │ 3.613 ms      │ 3.846 ms      │ 100     │ 100
│                                                          2.908 GB/s    │ 1.418 GB/s    │ 2.833 GB/s    │ 2.662 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            192         │ 194           │ 192           │ 195.1         │         │
│                                                            494.7 KB    │ 486.6 KB      │ 477.9 KB      │ 504.2 KB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            4359        │ 4343          │ 4355          │ 4348          │         │
│                                                            9.514 MB    │ 9.44 MB       │ 9.495 MB      │ 9.464 MB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            4359        │ 4343          │ 4355          │ 4348          │         │
│                                                            13.56 MB    │ 13.47 MB      │ 13.54 MB      │ 13.5 MB       │         │
│                                                          grow:         │               │               │               │         │
│                                                            504         │ 502           │ 504           │ 503.9         │         │
│                                                            4.046 MB    │ 4.03 MB       │ 4.046 MB      │ 4.045 MB      │         │
├─ http2_parallel_x10_req_10mb                             23.68 ms      │ 33.7 ms       │ 24.99 ms      │ 25.8 ms       │ 100     │ 100
│                                                          4.426 GB/s    │ 3.11 GB/s     │ 4.195 GB/s    │ 4.063 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            251         │ 234           │ 240           │ 238           │         │
│                                                            1.097 MB    │ 989.8 KB      │ 1.094 MB      │ 1.048 MB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            13162       │ 13161         │ 13162         │ 13162         │         │
│                                                            52.77 MB    │ 52.77 MB      │ 52.77 MB      │ 52.77 MB      │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            13162       │ 13161         │ 13162         │ 13161         │         │
│                                                            105.2 MB    │ 105.2 MB      │ 105.2 MB      │ 105.2 MB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            6420        │ 6421          │ 6420          │ 6420          │         │
│                                                            52.48 MB    │ 52.5 MB       │ 52.48 MB      │ 52.48 MB      │         │
├─ http2_parallel_x10_res_1mb                              2.416 ms      │ 3.978 ms      │ 2.478 ms      │ 2.571 ms      │ 100     │ 100
│                                                          4.338 GB/s    │ 2.635 GB/s    │ 4.23 GB/s     │ 4.077 GB/s    │         │
│                                                          max alloc:    │               │               │               │         │
│                                                            240         │ 240           │ 240           │ 239.4         │         │
│                                                            1.097 MB    │ 1.112 MB      │ 1.097 MB      │ 1.095 MB      │         │
│                                                          alloc:        │               │               │               │         │
│                                                            1572        │ 1572          │ 1572          │ 1572          │         │
│                                                            5.34 MB     │ 5.34 MB       │ 5.34 MB       │ 5.34 MB       │         │
│                                                          dealloc:      │               │               │               │         │
│                                                            1572        │ 1572          │ 1572          │ 1572          │         │
│                                                            10.58 MB    │ 10.58 MB      │ 10.58 MB      │ 10.58 MB      │         │
│                                                          grow:         │               │               │               │         │
│                                                            660         │ 661           │ 660           │ 660.2         │         │
│                                                            5.248 MB    │ 5.264 MB      │ 5.248 MB      │ 5.249 MB      │         │
╰─ http2_parallel_x10_res_10mb                             22.54 ms      │ 32.91 ms      │ 24.15 ms      │ 24.94 ms      │ 100     │ 100
                                                           4.65 GB/s     │ 3.185 GB/s    │ 4.34 GB/s     │ 4.203 GB/s    │         │
                                                           max alloc:    │               │               │               │         │
                                                             240         │ 240           │ 240           │ 238.8         │         │
                                                             1.097 MB    │ 1.097 MB      │ 1.097 MB      │ 1.098 MB      │         │
                                                           alloc:        │               │               │               │         │
                                                             13092       │ 13092         │ 13092         │ 13092         │         │
                                                             52.75 MB    │ 52.75 MB      │ 52.75 MB      │ 52.75 MB      │         │
                                                           dealloc:      │               │               │               │         │
                                                             13092       │ 13092         │ 13092         │ 13092         │         │
                                                             105.2 MB    │ 105.2 MB      │ 105.2 MB      │ 105.2 MB      │         │
                                                           grow:         │               │               │               │         │
                                                             6420        │ 6420          │ 6420          │ 6420          │         │
                                                             52.48 MB    │ 52.48 MB      │ 52.48 MB      │ 52.48 MB      │         │
```

**Comment by soundofspace** [comment]
@GlenDC fyi not sure how much we can trust these benchmarks. Sometimes running them suggested that this change increase speed by quite a bit and other times it did the opposite

**Comment by GlenDC** [comment]
> @GlenDC fyi not sure how much we can trust these benchmarks. Sometimes running them suggested that this change increased speed by quite a bit and other times it did the exact opposite. Either way looks like performance is pretty much the same as before

Isn’t that the nature of benchmarks. Which is why you usually run them several times etc.

Anyway that seems like a good enough conclusion for me.

**Comment by soundofspace** [comment]
> Isn’t that the nature of benchmarks. Which is why you usually run them several times etc.

Yea it is just mentioning it as an fyi, changes in speed where sometimes quite large. Would be nice if can test this in a more isolated way or have some graphs on this. Manually checking terminal output is far from ideal to notice changes

**Comment by GlenDC** [comment]
Agreed but that would be out of scope. Feel free to open a ticket. You can even contribute it to original crate first and propose it there. Gives some outside validation

File: benches/http_core_end_to_end.rs [hunk 1]
```diff
@@ -371,12 +362,20 @@ impl Opts {
...
-                Client::Http1(tx) => tx.send_request(req).await.expect("client wait h1"),
-                Client::Http2(tx) => tx.send_request(req).await.expect("client wait h2"),
+            let res = match shared_client {
+                Client::Http1(tx) => {
+                    let mut tx = tx.lock().await;
+                    tx.ready().await.expect("client is ready");
+                    tx.send_request(req).await.expect("client wait h1")
+                }
+                Client::Http2(tx) => {
+                    let mut tx = tx.clone();
```
Comment (GlenDC) [inline benches/http_core_end_to_end.rs:375]: Are you sure we want to clone this? I seems to have done this in the past I think and that proxy project using rama seemed to have significant increase of resources by cloning it instead of locking it.

Which is this revert commit: https://github.com/plabayo/rama/commit/e17dc0172b72d444d4135b308551a82dd20e3fa5

Comment (GlenDC) [reply benches/http_core_end_to_end.rs:375]: Ah but wait nvm this is not the core client, this is a bench, where you are cloning a channel. Ok should be okay I guess

File: rama-net/src/client/conn.rs [hunk 2]
```diff
@@ -81,3 +83,113 @@ where
         self.serve(ctx, req)
     }
 }
+
+/// Mock connector can be used in tests to simulate connectors so we can test client and servers
+/// without opening actuall connections
+pub struct MockConnectorService<S> {
```
Comment (GlenDC) [inline rama-net/src/client/conn.rs:89]: Can you please move this to some kind of module which name's makes it clear that this is a test utility.

File: rama-net/src/client/conn.rs [hunk 3]
```diff
@@ -81,3 +83,113 @@ where
...
+{
+    type Error = Infallible;
+    type Response = EstablishedClientConnection<MockSocket, State, Request>;
+
+    async fn serve(
+        &self,
+        ctx: Context<State>,
+        req: Request,
+    ) -> Result<Self::Response, Self::Error> {
+        let (client, server) = duplex(1024);
```
Comment (GlenDC) [inline rama-net/src/client/conn.rs:123]: might want to make this configurable, even if 1024 is the default?

File: rama-net/src/client/conn.rs [hunk 4]
```diff
@@ -81,3 +83,113 @@ where
...
+        std::pin::Pin::new(&mut self.stream).poll_flush(cx)
+    }
+
+    fn poll_shutdown(
+        mut self: std::pin::Pin<&mut Self>,
+        cx: &mut std::task::Context<'_>,
+    ) -> std::task::Poll<std::io::Result<()>> {
+        std::pin::Pin::new(&mut self.stream).poll_shutdown(cx)
+    }
+}
```
Comment (GlenDC) [inline rama-net/src/client/conn.rs:179]: Don't forget to also implement in your wrapper types such as this the provided trait methods:

// Provided methods
    fn [poll_write_vectored](https://docs.rs/tokio/latest/tokio/io/trait.AsyncWrite.html#method.poll_write_vectored)(
        self: [Pin](https://doc.rust-lang.org/nightly/core/pin/struct.Pin.html)<&mut Self>,
        cx: &mut [Context](https://doc.rust-lang.org/nightly/core/task/wake/struct.Context.html)<'_>,
        bufs: &[[IoSlice](https://doc.rust-lang.org/nightly/std/io/struct.IoSlice.html)<'_>],
    ) -> [Poll](https://doc.rust-lang.org/nightly/core/task/poll/enum.Poll.html)<[Result](https://doc.rust-lang.org/nightly/core/result/enum.Result.html)<[usize](https://doc.rust-lang.org/nightly/std/primitive.usize.html), [Error](https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html)>> { ... }
    fn [is_write_vectored](https://docs.rs/tokio/latest/tokio/io/trait.AsyncWrite.html#method.is_write_vectored)(&self) -> [bool](https://doc.rust-lang.org/nightly/std/primitive.bool.html) { ... }
}

File: rama-net/src/client/mod.rs [hunk 5]
```diff
@@ -2,7 +2,7 @@
 
 mod conn;
 #[doc(inline)]
-pub use conn::{ConnectorService, EstablishedClientConnection};
+pub use conn::{ConnectorService, EstablishedClientConnection, MockConnectorService};
```
Comment (GlenDC) [inline rama-net/src/client/mod.rs:5]: again I would expose this from within a separate module which makes it clear that it's a test utility

File: rama-http-backend/src/lib.rs [hunk 6]
```diff
@@ -17,3 +17,91 @@
...
+    use super::{client::HttpConnector, server::HttpServer};
+    use futures::future::join;
+    use rama_core::{Context, Service, rt::Executor, service::service_fn};
+    use rama_http_types::{Body, Request, Response, Version};
+    use rama_net::client::MockConnectorService;
+    use std::{
+        convert::Infallible,
+        time::{Duration, Instant},
+    };
+    use tokio::time::sleep;
```
Comment (GlenDC) [inline rama-http-backend/src/lib.rs:32]: each of these tests seem to only do 2 requests, is that sufficient to reliably trigger potential bugs?

**Review by GlenDC — CHANGES_REQUESTED** [review]
Looks mostly fine, only a couple of remarks. But we can probably merge soon.

File: rama-http-backend/src/lib.rs (hunk 6 above)
Comment (soundofspace) [reply rama-http-backend/src/lib.rs:32]: Yea I do think in the future we want to extend these tests a lot, same for all other network layers. But this specifically:
- Http1 will 100% error when starting to requests at the same time (the way async code is intertwined here always results in the second request being fired before the first one is ready, hence error if pipelining is not working
- Http2 will never be faster then 200 when doing 2 requests without multiplexing its just impossible time wise, so if it does work then we do multiplexing

**Review by GlenDC — APPROVED** [review]

**Comment by GlenDC** [comment]
LGTM, whenever you feel ready you are free to squash-merge it.
