### PR TITLE
Issue 504/integration  http2 parallel 10 sometimes crashes in ci on macos

### LINKED ISSUE #504: integration::http2_parallel_10 sometimes crashes in ci on macos
Not sure if something in our fork is causing this or this issue also exists in native hyper

```
failures:

---- integration::http2_parallel_10 stdout ----

thread 'integration::http2_parallel_10' panicked at tests/http-core/support/mod.rs:610:26:
called `Result::unwrap()` on an `Err` value: rama_http_core::Error(Io, Kind(NotConnected))

thread 'integration::http2_parallel_10' panicked at tests/http-core/support/mod.rs:459:25:
rama_http_core::Error(Io, Kind(ConnectionReset))

thread 'integration::http2_parallel_10' panicked at tests/http-core/support/mod.rs:459:25:
rama_http_core::Error(Io, Kind(ConnectionReset))

thread 'integration::http2_parallel_10' panicked at tests/http-core/support/mod.rs:459:25:
rama_http_core::Error(Io, Kind(ConnectionReset))

thread 'integration::http2_parallel_10' panicked at tests/http-core/support/mod.rs:459:25:
rama_http_core::Error(Io, Kind(ConnectionReset))

thread 'integration::http2_parallel_10' panicked at tests/http-core/support/mod.rs:459:25:
rama_http_core::Error(Io, Kind(ConnectionReset))

thread 'integration::http2_parallel_10' panicked at tests/http-core/support/mod.rs:462:48:
called `Result::unwrap()` on an `Err` value: rama_http_core::Error(Io, Kind(ConnectionReset))


failures:
    integration::http2_parallel_10
```

[logs_37080848341.zip](https://github.com/user-attachments/files/19719360/logs_37080848341.zip)

### PR DESCRIPTION
**Pull request by soundofspace**
Will hopefully fix #504

### CODE REVIEW

**Comment by soundofspace** [comment]
@GlenDC its possible to also replicate this locally, so if you ever see something like this know it might be related.

Tracing logs for reference
[out.log](https://github.com/user-attachments/files/19741791/out.log)

**Comment by soundofspace** [comment]
Depending on how you change this test, its pretty easy to also trigger this locally. 
Applying this change fixes it, and haven't been able to reproduce it.

File: rama-http-core/src/h2/codec/framed_write.rs [hunk 1]
```diff
@@ -170,7 +170,17 @@ where
             ready!(self.flush(cx))?;
             self.final_flush_done = true;
         }
-        Pin::new(&mut self.inner).poll_shutdown(cx)
+
+        // Mac OS and BSD variants can throw this error if shutdown was already called (eg by tcp reset).
+        // This is not a problem on linux since this error will be ignored inside the kernel.
+        // Catching this here will prevent this (harmless) error from blowing up.
+        // TODO: remove this once the root causes of this issue are fixed
+        // - https://github.com/tokio-rs/tokio/issues/4665
```
Comment (GlenDC) [inline rama-http-core/src/h2/codec/framed_write.rs:178]: Links need to be explicitly marked with angle brackets `<>`

File: rama-http-core/src/h2/codec/framed_write.rs [hunk 2]
```diff
@@ -170,7 +170,17 @@ where
...
+        // - https://github.com/hyperium/h2/issues/843
+        match ready!(Pin::new(&mut self.inner).poll_shutdown(cx)) {
```
Comment (GlenDC) [inline rama-http-core/src/h2/codec/framed_write.rs:180]: Can you please only do this for the impacted targets and do it "normally" for other targets

**Review by GlenDC — CHANGES_REQUESTED** [review]

File: rama-http-core/src/h2/codec/framed_write.rs (hunk 1 above)
Comment (soundofspace) [reply rama-http-core/src/h2/codec/framed_write.rs]: didn't know that was also done for inline comments, good to know

File: rama-http-core/src/h2/codec/framed_write.rs (hunk 2 above)
Comment (soundofspace) [reply rama-http-core/src/h2/codec/framed_write.rs:196]: done

**Review by GlenDC — APPROVED** [review]

**Comment by GlenDC** [comment]
Looks good. Once ci passes please merge unless you have a reason not to
